language: android
android:
  components:
    - build-tools-27.0.3

    # The SDK version used to compile your project
    - android-27

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-26

before_script:
  #cleanup everything, just in case
  ./gradlew clean

script:
  #simply build and run unit tests
  ./gradlew test